version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=local
    env_file:
      - .env.local
    restart: unless-stopped
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next